window.QUESTION_BANK = [
  {
    id: "B1-COL-001",
    cefr: "B1",
    category: "Collocation",
    domain: "Workplace",
    skill: "Recognition",
    type: "mcq",
    context: "Your manager gives you a task, but two requirements are unclear.",
    prompt: "Before starting the work, you should _____ the requirements with your manager.",
    options: ["clarify", "announce", "estimate", "invest"],
    answer: "clarify",
    knowledge: "clarify requirements",
    note: "clarify + requirements = 把需求釐清到可執行的程度。",
    example: "I clarified the requirements before asking the team to estimate the work."
  },
  {
    id: "B1-GRA-002",
    cefr: "B1",
    category: "Grammar",
    domain: "Workplace",
    skill: "Tense",
    type: "mcq",
    context: "You are describing a project that finished last month.",
    prompt: "We _____ the main cause of the drop-off by reviewing the session recordings.",
    options: ["identified", "identify", "have identify", "identifies"],
    answer: "identified",
    knowledge: "past tense in project stories",
    note: "已完成專案故事通常需要穩定使用過去式。",
    example: "We identified the main cause and simplified the flow."
  },
  {
    id: "B1-VOC-003",
    cefr: "B1",
    category: "Vocabulary",
    domain: "General",
    skill: "Recognition",
    type: "mcq",
    context: "You promised to send a document, but your colleague has not received it.",
    prompt: "Your colleague asks you to _____ them if there is any delay.",
    options: ["remind", "remember", "borrow", "avoid"],
    answer: "remind",
    knowledge: "remind someone",
    note: "remind + 人 = 提醒某人；remember = 自己記得。",
    example: "Please remind me if I forget to send the file."
  },
  {
    id: "B2-PM-004",
    cefr: "B2",
    category: "Vocabulary",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "The team has four possible features but only enough engineering capacity to build one this sprint.",
    prompt: "The PM needs to _____ the feature with the highest expected impact.",
    options: ["prioritize", "facilitate", "announce", "investigate"],
    answer: "prioritize",
    knowledge: "prioritize a feature",
    note: "prioritize = 根據價值、風險或資源決定優先順序。",
    example: "We prioritized the feature that addressed the largest user pain point."
  },
  {
    id: "B2-PM-005",
    cefr: "B2",
    category: "Collocation",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "A new onboarding idea looks promising, but the team has not tested whether users actually need it.",
    prompt: "Before investing more resources, we should _____ the assumption with user research.",
    options: ["validate", "allocate", "escalate", "facilitate"],
    answer: "validate",
    knowledge: "validate an assumption",
    note: "validate an assumption = 用證據驗證假設。",
    example: "We validated the assumption with five user interviews."
  },
  {
    id: "B1-GRA-006",
    cefr: "B1",
    category: "Grammar",
    domain: "General",
    skill: "Preposition",
    type: "mcq",
    context: "A release was postponed because a payment service stopped working.",
    prompt: "The release was delayed _____ a technical issue.",
    options: ["because of", "because", "although", "unless"],
    answer: "because of",
    knowledge: "because of + noun",
    note: "because of 後面接名詞；because 後面通常接完整子句。",
    example: "The launch was delayed because of a technical issue."
  },
  {
    id: "B1-COL-007",
    cefr: "B1",
    category: "Collocation",
    domain: "Workplace",
    skill: "Recognition",
    type: "mcq",
    context: "A customer reports a recurring checkout error.",
    prompt: "The team needs to _____ the issue before the next release.",
    options: ["address", "announce", "borrow", "attend"],
    answer: "address",
    knowledge: "address an issue",
    note: "address an issue = 著手處理問題；語氣比 fix 更廣，也更適合職場。",
    example: "We addressed the issue by simplifying the validation logic."
  },
  {
    id: "B2-PM-008",
    cefr: "B2",
    category: "Vocabulary",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "Design wants a richer experience, while engineering is concerned about delivery time.",
    prompt: "The PM should help both teams _____ on a realistic solution.",
    options: ["align", "estimate", "launch", "monitor"],
    answer: "align",
    knowledge: "align on a solution",
    note: "align on = 對某個方向形成共識。",
    example: "We aligned on a smaller scope for the first release."
  },
  {
    id: "B1-ACT-009",
    cefr: "B1",
    category: "Active Recall",
    domain: "Workplace",
    skill: "Productive",
    type: "typing",
    context: "請輸入最自然的英文動詞。",
    prompt: "「釐清需求」\n_____ the requirements",
    answer: "clarify",
    accepted: ["clarify"],
    knowledge: "clarify requirements",
    note: "把 clarify 與 requirements 綁在一起記，比單背 clarify 更容易在工作中叫得出來。",
    example: "First, I clarified the requirements with the sales team."
  },
  {
    id: "B2-ACT-010",
    cefr: "B2",
    category: "Active Recall",
    domain: "Product Management",
    skill: "Productive",
    type: "typing",
    context: "請輸入最自然的英文動詞。",
    prompt: "「驗證假設」\n_____ the assumption",
    answer: "validate",
    accepted: ["validate"],
    knowledge: "validate an assumption",
    note: "這是 Product / PM 很常用的搭配。",
    example: "We validated the assumption before building the feature."
  },
  {
    id: "B1-GRA-011",
    cefr: "B1",
    category: "Grammar",
    domain: "Workplace",
    skill: "Subject-verb agreement",
    type: "mcq",
    context: "You are describing a current product metric.",
    prompt: "The data _____ that most users leave during the verification step.",
    options: ["shows", "show", "showing", "have shown"],
    answer: "shows",
    knowledge: "subject-verb agreement",
    note: "在這個句型裡 data 被當成整體資料集合來描述時，商務英文常見用 shows。",
    example: "The data shows that most users leave at this step."
  },
  {
    id: "B1-GRA-012",
    cefr: "B1",
    category: "Grammar",
    domain: "General",
    skill: "Article",
    type: "mcq",
    context: "You are introducing a specific problem for the first time.",
    prompt: "We found _____ issue in the checkout flow.",
    options: ["an", "a", "the", "—"],
    answer: "an",
    knowledge: "article before singular countable noun",
    note: "單數可數名詞第一次提到通常需要 a/an；issue 以母音音素開頭，用 an。",
    example: "We found an issue in the checkout flow."
  },
  {
    id: "B1-PHR-013",
    cefr: "B1",
    category: "Phrasal Verb",
    domain: "Workplace",
    skill: "Recognition",
    type: "mcq",
    context: "A problem appears during a live demo, and you need to manage it calmly.",
    prompt: "I can _____ the issue first and investigate the root cause after the meeting.",
    options: ["deal with", "depend on", "result in", "point out"],
    answer: "deal with",
    knowledge: "deal with an issue",
    note: "deal with = 處理；很常見，但要避免所有情境都只用這一個泛用片語。",
    example: "I dealt with the urgent issue first, then investigated the cause."
  },
  {
    id: "B2-PM-014",
    cefr: "B2",
    category: "Vocabulary",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "The team wants to know whether a redesigned flow actually improved conversion after launch.",
    prompt: "We should _____ the impact for at least two weeks before making another change.",
    options: ["measure", "announce", "assign", "facilitate"],
    answer: "measure",
    knowledge: "measure impact",
    note: "measure impact / performance / conversion 都是很常見的工作搭配。",
    example: "We measured the impact after launch and saw a 12% improvement."
  },
  {
    id: "B2-PM-015",
    cefr: "B2",
    category: "Vocabulary",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "A release has several known risks. You cannot remove all of them, but you can reduce their likelihood or impact.",
    prompt: "The team created a fallback plan to _____ the release risk.",
    options: ["mitigate", "announce", "clarify", "attend"],
    answer: "mitigate",
    knowledge: "mitigate risk",
    note: "mitigate risk = 降低風險發生機率或影響程度。",
    example: "We added a rollback plan to mitigate the release risk."
  },
  {
    id: "B1-ACT-016",
    cefr: "B1",
    category: "Active Recall",
    domain: "Workplace",
    skill: "Productive",
    type: "typing",
    context: "請輸入最自然的英文動詞。",
    prompt: "「處理這個問題」\n_____ the issue",
    answer: "address",
    accepted: ["address", "handle"],
    knowledge: "address an issue",
    note: "address / handle 都可以；在描述改善與解決流程時，address 很實用。",
    example: "We addressed the issue in the next release."
  },
  {
    id: "B1-GRA-017",
    cefr: "B1",
    category: "Grammar",
    domain: "General",
    skill: "Conditionals",
    type: "mcq",
    context: "You are describing what you would do in a hypothetical future project.",
    prompt: "If I _____ the project again, I would involve users earlier.",
    options: ["did", "do", "will do", "have done"],
    answer: "did",
    knowledge: "second conditional",
    note: "If + past simple, would + verb 用來描述假設情境。",
    example: "If I did the project again, I would involve users earlier."
  },
  {
    id: "B2-PM-018",
    cefr: "B2",
    category: "Collocation",
    domain: "Product Management",
    skill: "Recognition",
    type: "mcq",
    context: "The roadmap depends on another platform team finishing an API first.",
    prompt: "The API team is a key _____ for our release plan.",
    options: ["dependency", "assumption", "trade-off", "metric"],
    answer: "dependency",
    knowledge: "project dependency",
    note: "dependency = 你的工作能否進行取決於另一件事或另一個團隊。",
    example: "We identified the API integration as a key dependency."
  },
  {
    id: "B2-ACT-019",
    cefr: "B2",
    category: "Active Recall",
    domain: "Product Management",
    skill: "Productive",
    type: "typing",
    context: "請輸入最自然的英文動詞。",
    prompt: "「衡量成效」\n_____ the impact",
    answer: "measure",
    accepted: ["measure"],
    knowledge: "measure impact",
    note: "面試敘述 Result 時，measure 是需要能主動叫出的核心動詞。",
    example: "We measured the impact after launch."
  },
  {
    id: "B1-VOC-020",
    cefr: "B1",
    category: "Vocabulary",
    domain: "General",
    skill: "Recognition",
    type: "mcq",
    context: "You want to join a workshop next Friday.",
    prompt: "I plan to _____ the workshop next Friday.",
    options: ["attend", "join in", "borrow", "avoid"],
    answer: "attend",
    knowledge: "attend an event",
    note: "attend + meeting/workshop/event；通常不需要介系詞。",
    example: "I attended the workshop last Friday."
  }
];
